/* Experience content is based on the user's Swiss Editorial Senior AI Engineer CV.
   Brand assets are downloaded from official websites; unverified brands use labeled initials. */
const jobs=[
{id:'hich',name:'Hich',logo:'hich.png',role:'AI Software Engineer',date:'Aug 2024 — Sep 2025',location:'Birmingham, UK · Remote',domain:'Social polling · Personalization & multimodal AI',link:'https://www.linkedin.com/company/hichapp/',headline:'Personalization, quality, and trust.',intro:'At Hich, my work connected recommendation systems, content understanding, and platform integrity. I built production ML systems around user behavior and moderator feedback, with monitoring tied to engagement and business outcomes.',flow:['User interactions & platform content','Recommendation, retrieval & quality models','Personalized content experiences','Grafana monitoring & feedback'],achievements:[['Recommendation infrastructure','Designed an event-driven platform using <strong>Kafka, ClickHouse, collaborative filtering, content-based ranking, and clustering</strong>. User activity increased by <strong>18%</strong>, post skipping fell by <strong>33%</strong>, and average usage increased by <strong>13%</strong>.'],['Multimodal fine-tuning','Fine-tuned <strong>LLaVA-1.6 Vicuna-7B with LoRA</strong> on <strong>1.7M moderator-labeled samples</strong> for automated content-quality scoring, achieving <strong>98.1% accuracy</strong>.'],['Retrieval & content generation','Built semantic retrieval over platform content for search, personalization, and LLM-assisted workflows. OpenAI-powered pipelines integrated external news sources, increasing interactions by <strong>14%</strong> and average session time by <strong>8%</strong>.'],['Fraud detection & production visibility','Built fraud detection and user-legitimacy scoring, improving content-quality accuracy by <strong>43%</strong> and monthly revenue by over <strong>60%</strong>. Implemented Grafana monitoring for model quality, engagement, system behavior, and business KPIs.']],metrics:[['1.7M','Moderator-labeled fine-tuning samples'],['98.1%','Content-quality scoring accuracy'],['+18%','User activity']]},
{id:'offerland',name:'Offerland',logo:'offerland.svg',role:'Machine Learning Engineer',date:'Jul 2022 — Aug 2024',location:'Vancouver, Canada · Remote',domain:'Property technology · Farmland valuation & rental intelligence',link:'https://www.linkedin.com/company/offerland/',headline:'Turning domain expertise into valuation models.',intro:'I worked directly with customers and farmland valuation specialists to understand how they assess land. Those workflows and decision criteria shaped OfferFarm, a production price-prediction platform grounded in regional, geographic, soil, and market signals.',flow:['Regional, soil & market signals','Valuation models & comparable properties','Customer-facing APIs','Drift detection & retraining'],achievements:[['OfferFarm prediction models','Developed farmland price prediction with <strong>ExtraTrees, XGBoost, and Random Forest</strong>, achieving <strong>94% accuracy</strong>.'],['Customer-informed improvements','Translated feedback into soil and location adjustments, <strong>kernel ridge regression</strong>, arable-acre computation using <strong>Google APIs</strong>, and improved comparable-property selection.'],['Model operations','Built <strong>concept-drift detection, automated retraining triggers, operational alerts, and Metabase dashboards</strong> for model performance, pricing trends, customer activity, and usage.'],['APIs & rental intelligence','Reduced API latency by over <strong>60%</strong> with asynchronous requests and <strong>Redis caching</strong>. Engineered <strong>Offervista</strong> rental-trend pipelines covering <strong>93%+</strong> of Canadian postal codes.']],metrics:[['94%','Reported valuation accuracy'],['>60%','Lower API latency'],['93%+','Canadian postal-code coverage']]},
{id:'forsat',name:'Forsat Co',initials:'F',role:'Computer Vision Engineer / Technical Lead',date:'Sep 2021 — Jul 2022',location:'Tehran, Iran',domain:'Computer vision · Signature detection & verification',link:'https://www.linkedin.com/company/forsat/',headline:'From cheque images to deployed verification.',intro:'I led the computer-vision workstream and worked directly with customers on operational constraints, installation, and rollout. The work spanned dataset expansion, signature detection, forgery verification, and inference on customer machines.',flow:['Cheque image','YOLOv5 signature detection','SigNet-based forgery verification','FastAPI on customer infrastructure'],achievements:[['Data collection & augmentation','Expanded a <strong>300K-image signature dataset to 2M diverse samples</strong> through data collection and augmentation.'],['Signature detection','Developed a cheque-signature detection pipeline with <strong>YOLOv5, PyTorch, and a custom autoencoder</strong>, achieving <strong>96% mAP</strong>.'],['Verification & deployment','Implemented <strong>SigNet-based forgery detection</strong> with <strong>92.7% accuracy</strong> and deployed <strong>FastAPI inference services</strong> adapted to customer infrastructure.'],['Customer delivery','Worked with customers to understand operational constraints, install solutions in their environments, and support production rollout.']],metrics:[['2M','Augmented signature samples'],['96%','Signature-detection mAP'],['92.7%','Forgery-detection accuracy']]},
{id:'bale',name:'Bale Messenger',logo:'bale.svg',role:'Data Scientist',date:'Jan 2021 — Dec 2021',location:'Tehran, Iran',domain:'Messaging · Channel discovery & banking NLP',link:'https://www.linkedin.com/company/balemessenger/',headline:'Better discovery. More useful answers.',intro:'My work at Bale covered two user-facing problems: helping people discover relevant channels and answering banking questions through a fine-tuned language model.',flow:['Channel recommendation → channel discovery','Banking questions → fine-tuned ParsBERT','User engagement & answer accuracy'],achievements:[['Channel recommendations','Launched a recommendation system that increased channel joins by <strong>41%</strong> and brought average in-app time to <strong>8 minutes</strong>.'],['Banking question answering','Fine-tuned <strong>ParsBERT</strong> for a banking QA chatbot, achieving <strong>92% accuracy</strong>.']],metrics:[['+41%','Channel joins'],['8 min','Average in-app time'],['92%','Banking QA accuracy']]},
{id:'yektanet',name:'Yektanet',logo:'yektanet.png',role:'Data Scientist',date:'Mar 2020 — Jan 2021',location:'Tehran, Iran',domain:'Advertising technology · Recommendations & product discovery',link:'https://www.linkedin.com/company/yektanet/',headline:'Recommendations with measurable business impact.',intro:'I worked on recommendation and product-bundling systems, connecting relevance improvements to conversion and click-through outcomes.',flow:['Product recommendations → conversions','Association rules → product bundles','Conversion rate & click-through measurement'],achievements:[['Recommendation systems','Implemented recommendation systems that increased conversion rate by <strong>58%</strong>.'],['Product bundling','Built <strong>association-rule product-bundling algorithms</strong> that increased click-through rate by <strong>25%</strong>.']],metrics:[['+58%','Conversion rate'],['+25%','Product-bundling CTR']]},
{id:'shanikala',name:'ShaniKala',initials:'SK',role:'Software Engineer',date:'Mar 2018 — Dec 2019',location:'Tehran, Iran',domain:'E-commerce · Backend systems & marketplace integrations',link:'https://www.linkedin.com/company/shanikala/',headline:'Building the foundations of a commerce platform.',intro:'My software-engineering foundation came from building backend features, customer-facing APIs, marketplace integrations, and recommendation features for e-commerce.',flow:['Backend features & customer APIs','Marketplace integrations','Similar-product recommendations'],achievements:[['Commerce infrastructure','Developed backend and integration features using <strong>ASP.NET, .NET Core, MSSQL, and NopCommerce</strong>.'],['Product discovery','Built recommendation features that increased similar-product click-through rate by <strong>37%</strong>.']],metrics:[['+37%','Similar-product CTR']]}
];
const hero=document.querySelector('.hero');
hero.innerHTML=`<div><div class="eyebrow availability"><span class="dot"></span>Senior AI Engineer · Heidelberg, Germany</div><h1 id="hero-title">Hi, I’m Mohsen.<br><span>I build AI systems.</span></h1><p class="intro">I’m an AI engineer working across agent architectures, machine learning, and the infrastructure that brings them into production. I enjoy understanding how a system behaves—and building the tools to make it better.</p><div class="hero-links"><a class="primary-link" href="#work">Explore my background <span class="arrow">↓</span></a><a href="https://github.com/mohsenshahverdy" target="_blank" rel="noopener noreferrer">GitHub ↗</a></div></div><aside class="about-aside"><div class="eyebrow">A little about me</div><p>My background spans <strong>e-commerce, recommendations, computer vision, and production ML</strong>. Today, at Lensing AI, I design agent infrastructure within the AISpecify Build/Compiler team.</p><p>Alongside engineering, I’ve researched <strong>communication-aware perception</strong> during my master’s at Politecnico di Milano. I’m interested in the decisions that connect an experiment to a system people can use.</p><span class="mono">Software foundations → ML systems → Agent infrastructure</span></aside>`;
document.querySelector('nav a').textContent='Background';
const work=document.getElementById('work');work.setAttribute('aria-labelledby','background-title');
const bar=work.querySelector('.section-bar');bar.innerHTML='<span class="eyebrow">01 / My background</span><span class="right">2018 — Present · Engineering & applied research</span>';
const intro=document.createElement('div');intro.className='background-intro';intro.innerHTML='<h2 id="background-title">The work behind the journey.</h2><p>Open a company to explore the problems, systems, and outcomes from that chapter.</p>';
function summary(j){return `<summary><span class="company-logo ${j.logo?'':'initials'}" ${j.logo?'':`title="${j.name} initials — logo pending verification"`}>${j.logo?`<img src="assets/${j.logo}" alt="${j.name} logo">`:j.initials}</span><span><span class="company-title">${j.name}</span><span class="company-role">${j.role}</span><span class="company-domain">${j.domain}</span></span><span class="company-date">${j.date}<small>${j.location}</small></span><span class="company-toggle" aria-hidden="true"></span></summary>`}
const lensing={name:'Lensing AI',logo:'lensing.png',role:'Senior AI Engineer · Agentic AI Systems',date:'Sep 2025 — Present',location:'Heidelberg, Germany',domain:'AISpecify · AI compiler & enterprise application generation'};
const list=document.createElement('div');list.className='company-list';
const lc=document.createElement('details');lc.className='company-card';lc.id='lensing';lc.innerHTML=summary(lensing);const lbody=document.createElement('div');lbody.className='company-content';
[...work.children].filter(el=>el!==bar).forEach(el=>lbody.append(el));
const source=document.createElement('div');source.className='company-source';source.innerHTML='<span>Formerly Everest Systems GmbH · Build/Compiler team</span><a href="https://www.linkedin.com/company/lensing-ai/" target="_blank" rel="noopener noreferrer">About Lensing AI ↗</a>';lbody.append(source);lc.append(lbody);list.append(lc);
jobs.forEach(j=>{const card=document.createElement('details');card.className='company-card';card.id=j.id;card.innerHTML=summary(j)+`<div class="company-content"><div class="company-story"><div><div class="eyebrow">${j.name} / Engineering story</div><h3>${j.headline}</h3><p>${j.intro}</p></div><div class="mini-flow"><div class="eyebrow">A view of the work</div>${j.flow.map((s,i)=>`<div class="flow-item"><span>0${i+1}</span>${s}</div>`).join('')}<small>Conceptual overview of my work; not an internal architecture diagram.</small></div></div><div class="achievement-grid">${j.achievements.map(([title,body])=>`<article class="achievement"><h4>${title}</h4><p>${body}</p></article>`).join('')}</div><div class="outcomes">${j.metrics.map(([v,label])=>`<div class="metric"><div class="metric-value blue">${v}</div><p>${label}</p></div>`).join('')}</div><div class="company-source"><span>Role details and reported outcomes from my experience.</span><a href="${j.link}" target="_blank" rel="noopener noreferrer">About ${j.name} ↗</a></div></div>`;list.append(card)});
work.append(intro,list);
const note=document.createElement('p');note.className='logo-note';note.textContent='Forsat and ShaniKala currently use initials; their official logos are pending verification.';work.append(note);
const scholar='https://scholar.google.com/citations?view_op=view_citation&hl=en&user=B69XFvQAAAAJ&citation_for_view=B69XFvQAAAAJ:u5HHmVD_uO8C';
const researchProjects=[
{id:'research-v2v',initials:'01',name:'Communication-aware cooperative perception',role:'Master’s thesis · Politecnico di Milano',domain:'3D perception · Information sharing · Experimental evaluation',date:'Master’s research',location:'AI & machine learning',body:`<div class="company-story"><div><div class="eyebrow">The research question</div><h3>What should one vehicle share with another?</h3><p>My master’s research investigates how cooperating vehicles can exchange relevant information for 3D object detection while controlling communication cost.</p><p>I explore receiver-driven information sharing, temporal policies, and evaluation of detection quality and communication overhead.</p></div><div class="mini-flow"><div class="eyebrow">Experimental focus</div><div class="flow-item"><span>01</span>Cooperative 3D perception</div><div class="flow-item"><span>02</span>Receiver-driven & temporal sharing policies</div><div class="flow-item"><span>03</span>Detection quality & communication evaluation</div><small>Public code and an interactive research presentation are available below.</small></div></div><div class="research-links"><a href="https://github.com/mohsenshahverdy/comm-aware-v2v-perception" target="_blank" rel="noopener noreferrer">Research repository ↗</a><a href="https://github.com/mohsenshahverdy/receiver-driven-sparse-v2v-3D-presentation" target="_blank" rel="noopener noreferrer">3D research presentation ↗</a></div>`},
{id:'research-bsc',initials:'02',name:'Machine learning for clinical decision support',role:'Bachelor’s thesis · Shahid Beheshti University',domain:'Interpretable ML · Best BSc Thesis award',date:'Published 2021',location:'Archives of Academic Emergency Medicine',body:`<div class="company-story"><div><div class="eyebrow">Bachelor’s thesis / Published research</div><h3>Can interpretable ML help assess the need for a CT scan?</h3><p>My bachelor’s thesis focused on applying AI and machine learning to clinical decision support. The resulting study compared seven classification approaches using a dataset of <strong>1,000 trauma patients</strong>, selecting an interpretable decision-tree model.</p><p><strong>Best BSc Thesis — Shahid Beheshti University.</strong></p></div><div class="mini-flow"><div class="eyebrow">Publication</div><p class="publication-title">Determining the Need for Computed Tomography Scan Following Blunt Chest Trauma through Machine Learning Approaches</p><p class="publication-meta">Mohsen Shahverdi Kondori · Hamed Malek<br>Archives of Academic Emergency Medicine<br>2021 · 9(1): e15</p><small>Research study; no claim of clinical deployment.</small></div></div><div class="research-links"><a href="${scholar}" target="_blank" rel="noopener noreferrer">Google Scholar ↗</a><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC7927753/" target="_blank" rel="noopener noreferrer">Read the paper ↗</a></div>`}
];
const degrees=[
{id:'education-masters',initials:'M',name:'Politecnico di Milano',role:'Master of Engineering — Artificial Intelligence Focus',domain:'Machine learning · Deep learning · Computer vision · NLP',date:'Sep 2022 — Jun 2025',location:'Milan, Italy',body:`<div class="company-story"><div><div class="eyebrow">Academic focus</div><h3>Advanced study in AI and machine learning.</h3><p>Focused my studies on machine learning, deep learning, computer vision, and natural language processing, connecting theoretical foundations with experimental work.</p><p class="degree-program">Degree program: Telecommunication Engineering.</p></div><div><div class="eyebrow">Selected coursework</div><p>Machine Learning · Deep Learning · Advanced Computer Vision · NLP · Uncertainty in AI · Recommender Systems · Data Mining · Streaming Data Analysis · Advanced Signal Processing and Learning.</p><div class="research-links"><a href="#research-v2v" data-open-card="research-v2v">Explore my master’s research ↓</a></div></div></div>`},
{id:'education-bachelors',initials:'B',name:'Shahid Beheshti University',role:'Bachelor of Science — Computer Engineering',domain:'AI & ML focus · Best BSc Thesis award',date:'Sep 2015 — Feb 2020',location:'Tehran, Iran',body:`<div class="company-story"><div><div class="eyebrow">Academic focus</div><h3>A foundation in AI, ML, and software engineering.</h3><p>My main focus was <strong>artificial intelligence and machine learning</strong>, supported by coursework in computer vision, computational intelligence, data mining, algorithms, and statistics.</p><p><strong>Best BSc Thesis — Shahid Beheshti University</strong>, for my bachelor’s research in machine learning for clinical decision support.</p></div><div><div class="eyebrow">Selected coursework</div><p>Artificial Intelligence · Computer Vision · Computational Intelligence · Data Mining · Data Structures · Algorithms · Signal Processing · Statistics · Calculus.</p><div class="research-links"><a href="#research-bsc" data-open-card="research-bsc">Explore my bachelor’s research ↓</a></div></div></div>`}
];
function academicSection(id,title,subtitle,items){return `<section id="${id}" aria-labelledby="${id}-heading"><div class="section-bar"><span class="eyebrow" id="${id}-heading">${title}</span><span class="right">${subtitle}</span></div><div class="academic-list">${items.map(j=>`<details class="company-card research-card" id="${j.id}">${summary(j)}<div class="company-content">${j.body}</div></details>`).join('')}</div></section>`}
document.querySelector('.next').outerHTML=academicSection('research','02 / Research projects','Questions, experiments, and published work',researchProjects)+academicSection('education','03 / Education','An AI & ML-focused academic foundation',degrees);
document.querySelectorAll('[data-open-card]').forEach(a=>a.addEventListener('click',()=>{document.getElementById(a.dataset.openCard).open=true}));
const skip=document.createElement('a');skip.className='skip-link';skip.href='#work';skip.textContent='Skip to background';document.body.prepend(skip);
// Native details/summary supports keyboard and touch, and allows comparing chapters.
// Stop the illustrative replay when its parent chapter is closed.
lc.addEventListener('toggle',()=>{if(!lc.open)stop()});
const themeControl=document.createElement('div');themeControl.className='theme-control';themeControl.setAttribute('role','group');themeControl.setAttribute('aria-label','Color theme');themeControl.innerHTML='<button type="button" data-theme="dark" aria-pressed="true">Dark</button><button type="button" data-theme="light" aria-pressed="false">Light</button>';document.querySelector('nav').append(themeControl);
function setTheme(theme){document.documentElement.dataset.theme=theme;themeControl.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.theme===theme)))}
setTheme('dark');themeControl.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>setTheme(b.dataset.theme)));
const cvLink=document.createElement('a');cvLink.href='assets/Mohsen-Shahverdi-Senior-AI-Engineer-CV.pdf';cvLink.download='Mohsen-Shahverdi-Senior-AI-Engineer-CV.pdf';cvLink.textContent='Download CV ↓';cvLink.setAttribute('aria-label','Download Senior AI Engineer CV as PDF');document.querySelector('.hero-links').append(cvLink);document.querySelector('.footer-links').append(cvLink.cloneNode(true));
