(() => {
// Keep Hich's three subsystems and remove only the requested lower items 04–06.
document.querySelectorAll('#hich .system-copy article').forEach((el,i)=>{if(i>=3)el.remove()});
const offer=document.querySelector('#offerland .company-content');
offer.innerHTML=`<div class="architecture-intro"><div class="eyebrow">Offerland / OfferFarm</div><h3>A farm’s value, viewed two ways.</h3><p>I built a farmland valuation pipeline that combines <strong>tree-based price prediction</strong> with a second view derived from <strong>nearby, similar farms</strong>. Working with customers and farmland valuation specialists helped translate real appraisal workflows into model features, comparable-property selection, and useful outputs.</p></div>
<div class="feature-strip" aria-label="Valuation feature families"><span>Farm-specific attributes</span><span>Availability</span><span>Location & geography</span><span>Soil characteristics</span><span>Arable acreage</span><span>Regional market signals</span></div>
<div class="case-visual"><figure class="farm-scene"><img src="assets/farmland-overhead.jpg" alt="Top-down aerial view of agricultural plots and field boundaries" loading="lazy"><div class="map-label">PROPERTY INTELLIGENCE / ILLUSTRATIVE EXAMPLE</div><div class="property-cards"><article class="land-card subject"><small>SUBJECT FARM</small><h4>Property profile</h4><dl><div><dt>Parcel size</dt><dd>160 acres</dd></div><div><dt>Arable land</dt><dd>84%</dd></div><div><dt>Soil quality</dt><dd>High</dd></div><div><dt>Avg. annual rainfall</dt><dd>720 mm</dd></div><div><dt>Location factor</dt><dd>1.04×</dd></div></dl></article><article class="land-card comp-a"><small>COMPARABLE A / 2.4 km</small><h4>Similar soil profile</h4><p>148 acres · 81% arable</p><span>Soil: high · Location: 1.02×</span></article><article class="land-card comp-b"><small>COMPARABLE B / 4.1 km</small><h4>Similar usable acreage</h4><p>172 acres · 79% arable</p><span>Soil: high · Rainfall: 690 mm</span></article><article class="land-card comp-c"><small>COMPARABLE C / 5.8 km</small><h4>Nearby market evidence</h4><p>155 acres · 86% arable</p><span>Soil: medium-high · Location: 0.98×</span></article></div><figcaption>All cards, values, and locations are fictional examples—not actual property data or a product screenshot.<br>Photo: <a href="https://unsplash.com/photos/a-large-field-of-crops-nluH_zF2p_M" target="_blank" rel="noopener noreferrer">Timon Reinhard / Unsplash ↗</a></figcaption></figure>
<div class="price-methods"><article class="price-method"><div class="eyebrow">Output 01 / Model estimate</div><h4>Predicted Price</h4><p>Farm features enter a <strong>tree-based model</strong> to estimate the farm’s price. The modeling work included ExtraTrees, XGBoost, and Random Forest, combining farm-specific information with geographic, soil, and market attributes.</p><div class="result">Farm features → Tree-based model → Predicted Price</div></article><article class="price-method"><div class="eyebrow">Output 02 / Comparable evidence</div><h4>Adjusted Average Comparable Price</h4><p>Identify nearby farms with the highest similarity, adjust their prices relative to the predicted price, then average the adjusted values. This produces a separate comparable-based output alongside the model estimate.</p><div class="result">Nearby similar farms → Adjust prices → Average</div></article></div></div>
<section class="evaluation-lab" aria-labelledby="evaluation-title"><div class="eval-header"><div><div class="eyebrow">Model lifecycle / Interactive walkthrough</div><h4 id="evaluation-title">When the data changes, the model adapts.</h4></div><button id="drift-demo" type="button">Replay drift response ↗</button></div><div class="eval-stages" role="group" aria-label="Automatic model lifecycle stages">${['Detect drift','Preprocess','Retrain','Evaluate','Replace model'].map((s,i)=>`<button class="eval-stage" type="button" data-eval="${i}" aria-pressed="${i===0}"><small>0${i+1}</small>${s}</button>`).join('')}</div><div class="eval-detail"><div class="lifecycle-visual"><canvas class="drift-plot" role="img" aria-label="Illustrative distributions: reference data and shifted incoming data. Not measured results."></canvas><div id="lifecycle-diagram"></div></div><div class="eval-explanation" aria-live="polite"><h5 id="eval-title"></h5><p id="eval-body"></p></div></div><p class="eval-caption">Conceptual walkthrough. Diagrams and candidate rankings are illustrative—not production data, measured errors, or a named statistical test.</p></section>
<details class="compact-details"><summary>Modeling refinements & production engineering</summary><p>Customer feedback informed soil and location adjustments, kernel ridge regression refinements, precise arable-acre computation through Google APIs, and improved comparable-farm selection. I built statistical concept-drift detection, automatic retraining triggers, alerts, and Metabase dashboards for model performance, pricing trends, and usage.</p><p>Asynchronous requests and Redis caching reduced API latency by over 60%. Offervista rental-trend pipelines covered 93%+ of Canadian postal codes.</p></details><div class="outcomes"><div class="metric"><div class="metric-value blue">94%</div><p>Reported valuation accuracy</p></div><div class="metric"><div class="metric-value blue">&gt;60%</div><p>Lower API latency</p></div></div><div class="company-source"><span>Offerland · Machine Learning Engineer · Vancouver, Canada (Remote)</span><a href="https://www.linkedin.com/company/offerland/" target="_blank" rel="noopener noreferrer">About Offerland ↗</a></div>`;
const descriptions=[['Statistically detect concept drift.','The system monitors for drift in incoming data. Statistical detection automatically triggers the retraining pipeline when drift is identified.'],['Prepare the updated data.','The triggered pipeline handles preprocessing and the related data-preparation steps before training new model candidates.'],['Train candidate models.','The retraining pipeline learns from the prepared data, producing new candidates for the farm-price prediction task.'],['Compare candidates through evaluation.','The pipeline evaluates the new models and identifies the best candidate. Evaluation is a distinct step before model replacement.'],['Replace the existing model.','The best new model replaces the existing model after evaluation, completing the automatic drift-response cycle.']];

const chain=(items)=>'<div class="process-chain">'+items.map((t,i)=>'<div class="process-node">'+t+'</div>'+(i<items.length-1?'<span aria-hidden="true">↓</span>':'')).join('')+'</div>';
function drawLifecycle(i){
const plot=document.querySelector('.drift-plot'),target=document.getElementById('lifecycle-diagram');
plot.hidden=i!==0;target.hidden=i===0;
const diagrams=[
'',
'<div class="diagram-kicker">DATA → MODEL-READY FEATURES</div>'+chain(['Updated farm records','Preprocess & prepare attributes','Aligned feature set'])+'<div class="feature-tokens"><span>Land & soil</span><span>Availability</span><span>Location</span></div>',
'<div class="diagram-kicker">TRAIN → COMPARE CANDIDATES</div><div class="process-node">Prepared training data</div><div class="branch-stem">↓</div><div class="model-branches"><span>ExtraTrees</span><span>XGBoost</span><span>Random Forest</span></div><div class="branch-stem">↓</div><div class="process-node">Trained model candidates</div>',
'<div class="diagram-kicker">PREDICTIONS ↔ OBSERVED PRICES</div><div class="evaluation-pair"><span>Predicted prices</span><span>Observed prices</span></div><div class="branch-stem">↓</div><div class="process-node">Evaluate prediction error</div><div class="candidate-ranks"><div><span>Candidate A</span><i style="--bar:72%"></i></div><div class="best"><span>Candidate B</span><i style="--bar:35%"></i></div><div><span>Candidate C</span><i style="--bar:54%"></i></div></div><small class="diagram-note">Illustrative error comparison · lower is better</small>',
'<div class="diagram-kicker">SELECT → REPLACE → SERVE</div>'+chain(['Best evaluated candidate','Replace existing model','Updated price predictions'])+'<div class="monitor-loop">↺ Continue monitoring for drift</div>'
];target.innerHTML=diagrams[i];if(i===0)drift();
}

let evalIndex=0,evalTimer=null;const eb=[...document.querySelectorAll('[data-eval]')],replay=document.getElementById('drift-demo');
function setEval(i){evalIndex=i;eb.forEach((b,n)=>b.setAttribute('aria-pressed',String(n===i)));document.getElementById('eval-title').textContent=descriptions[i][0];document.getElementById('eval-body').textContent=descriptions[i][1];drawLifecycle(i)}
function stopEval(){clearTimeout(evalTimer);evalTimer=null;replay.disabled=false;replay.textContent='Replay drift response ↗'}
eb.forEach((b,i)=>b.addEventListener('click',()=>{stopEval();setEval(i)}));replay.addEventListener('click',()=>{stopEval();replay.disabled=true;replay.textContent='Playing…';let i=0;function advance(){setEval(i++);if(i<5)evalTimer=setTimeout(advance,1500);else stopEval()}advance()});document.getElementById('offerland').addEventListener('toggle',e=>{if(!e.target.open)stopEval()});setEval(0);
const forsat=document.querySelector('#forsat .company-content');
forsat.innerHTML=`<div class="architecture-intro"><div class="eyebrow">Forsat / Signature verification</div><h3>Find the signature. Isolate it. Compare it.</h3><p>I led the computer-vision workstream from signature collection and sample generation to customer deployment. The pipeline combined <strong>YOLO detection, a trained custom encoder for background removal, and SigNet—a Siamese Network—for signature similarity</strong>.</p></div><div class="dataset-banner"><span class="dataset-number">2M</span><p><strong>Generated cheque samples across different templates and visual formats.</strong><br>We collected user signatures and used them to generate the samples. The dataset also contained many intentionally forged signatures created by imitating genuine users’ signatures.</p></div>
<div class="signature-gallery"><article class="signature-step"><div class="eyebrow">01 / Locate</div><h4>YOLO signature detection</h4><canvas class="signature-canvas" data-sign="cheque" role="img" aria-label="Synthetic specimen cheque showing an illustrative signature bounding box"></canvas><p>YOLO detects the signature’s location on the cheque and provides the bounding box for the next stage.</p></article><article class="signature-step"><div class="eyebrow">02 / Clean</div><h4>Custom encoder</h4><canvas class="signature-canvas" data-sign="clean" role="img" aria-label="Illustrative signature strokes isolated from the cheque background"></canvas><p>A custom encoder that we trained removes background content from the detected bounding box, isolating the signature.</p></article><article class="signature-step"><div class="eyebrow">03 / Compare</div><h4>SigNet Siamese Network</h4><canvas class="signature-canvas" data-sign="compare" role="img" aria-label="Two synthetic signature samples compared through a shared Siamese model"></canvas><p>SigNet compares the cleaned cheque signature with the user’s original signature to measure their similarity.</p></article></div><p class="map-caption">Synthetic visual specimens drawn for this explanation. No real signatures, account details, financial documents, or model scores are shown.</p><p class="comparison-note">The similarity comparison supports identifying the cheque’s owner and deciding whether its signature is genuine or forged. Intentionally imitated signatures provide challenging examples for the verification task.</p><details class="compact-details"><summary>Dataset, model performance & customer rollout</summary><p>The work expanded a 300K-image signature dataset into two million generated cheque samples. The detection pipeline used YOLOv5 and PyTorch and achieved 96% mAP. SigNet-based forgery detection achieved 92.7% accuracy.</p><p>I worked directly with customers on operational constraints, installation, and production rollout, deploying FastAPI inference services adapted to their infrastructure.</p></details><div class="outcomes"><div class="metric"><div class="metric-value blue">2M</div><p>Generated cheque samples</p></div><div class="metric"><div class="metric-value blue">96%</div><p>Signature detection mAP</p></div><div class="metric"><div class="metric-value blue">92.7%</div><p>Forgery detection accuracy</p></div></div><div class="company-source"><span>Forsat · Computer Vision Engineer / Technical Lead · Tehran, Iran</span><a href="https://www.linkedin.com/company/forsat/" target="_blank" rel="noopener noreferrer">About Forsat ↗</a></div>`;
function renderCanvas(c,draw){const r=c.getBoundingClientRect();if(!r.width)return;const d=Math.min(devicePixelRatio||1,2);c.width=r.width*d;c.height=r.height*d;const x=c.getContext('2d');x.scale(d,d);draw(x,r.width,r.height)}
function drift(){renderCanvas(document.querySelector('.drift-plot'),(x,w,h)=>{const light=document.documentElement.dataset.theme==='light';x.font='9px monospace';x.fillStyle=light?'#556b7b':'#a1b4c3';x.fillText('REFERENCE',13,19);x.fillStyle=light?'#28628e':'#9cc9ef';x.fillText('INCOMING',w-85,19);x.strokeStyle=light?'#bccbd7':'#3b4f5e';x.beginPath();x.moveTo(15,h-23);x.lineTo(w-15,h-23);x.stroke();[.35,.62].forEach((mu,i)=>{x.strokeStyle=i?(light?'#28628e':'#9cc9ef'):'#84939e';x.setLineDash(i?[]:[4,4]);x.lineWidth=2;x.beginPath();for(let n=0;n<=100;n++){const t=n/100,y=h-24-75*Math.exp(-Math.pow((t-mu)/.16,2));if(!n)x.moveTo(15+t*(w-30),y);else x.lineTo(15+t*(w-30),y)}x.stroke()});x.setLineDash([])})}
function scribble(x,left,top,scale){x.save();x.translate(left,top);x.scale(scale,scale);x.strokeStyle='#284a68';x.lineWidth=1.8;x.beginPath();x.moveTo(0,22);x.bezierCurveTo(14,-10,22,40,29,14);x.bezierCurveTo(45,-25,18,55,48,22);x.bezierCurveTo(61,2,62,32,79,18);x.bezierCurveTo(91,8,89,29,108,14);x.moveTo(5,34);x.lineTo(115,28);x.stroke();x.restore()}
function signatures(){document.querySelectorAll('[data-sign]').forEach(c=>renderCanvas(c,(x,w,h)=>{x.fillStyle='#f4f2e8';x.fillRect(0,0,w,h);const k=c.dataset.sign;if(k==='cheque'){x.strokeStyle='#d8d9cd';for(let y=35;y<120;y+=21){x.beginPath();x.moveTo(12,y);x.lineTo(w-12,y);x.stroke()}x.font='9px monospace';x.fillStyle='#727c78';x.fillText('SPECIMEN / NOT VALID',12,20);x.fillText('PAY TO __________________',12,48);x.strokeStyle='#367ca1';x.strokeRect(w*.37,62,w*.56,58);scribble(x,w*.4,70,w*.004)}else if(k==='clean'){scribble(x,w*.2,40,w*.005);x.font='9px monospace';x.fillStyle='#727c78';x.fillText('ISOLATED SIGNATURE',12,20)}else{const s=w*.0034;scribble(x,14,26,s);scribble(x,w*.54,26,s);x.font='8px monospace';x.fillStyle='#526879';x.fillText('REFERENCE',14,19);x.fillText('CHEQUE',w*.54,19);x.strokeStyle='#aac0ce';x.strokeRect(w*.2,93,w*.6,25);x.fillText('SHARED MODEL → SIMILARITY',w*.21,109)}}))}
const observer=new ResizeObserver(()=>{drift();signatures()});observer.observe(document.querySelector('.drift-plot'));document.querySelectorAll('[data-sign]').forEach(c=>observer.observe(c));new MutationObserver(drift).observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});
})();
