(() => {
// Public portfolio abstraction based on the owner's account; not internal service documentation.
const lensing=document.querySelector('#lensing .company-content');
lensing.querySelector('.case-heading p').innerHTML='AISpecify turns specifications and business context into <strong>modular, ERP-integrated enterprise applications</strong>. Within Lensing AI’s Build/Compiler team, I architected and implemented compiler infrastructure that coordinates agents, application artifacts, enterprise APIs, validation, and repair.';
const context=document.createElement('p');context.className='service-context';context.innerHTML='<strong>The service context:</strong> an enterprise application needs connected modules, internal and external APIs, complex business logic, and unit and E2E tests. The compiler must coordinate those dependencies across generation—not simply produce independent pages.';lensing.querySelector('.workbench').before(context);
Object.assign(content.spec,{title:'Translate business intent into a build.',body:'Within AISpecify, I work across specification generation, building agents, and feedback mechanisms. Specifications and business context guide the generation of modular applications connected to the ERP system.',why:'Business rules, application modules, and integration requirements need a shared reference throughout generation.',trace:'01 · Map the enterprise specification to modules and integration requirements.'});
Object.assign(content.graph,{why:'Connected enterprise artifacts require dependency-aware task ordering, execution planning, and model/tool selection.',trace:'02 · Resolve dependencies among application artifacts, agents, and tools.'});
Object.assign(content.agents,{body:'I built a plugin-based agent harness and agent-loop foundations for other teams, alongside graph-driven context selection, business-context injection, and conversation-state management for LLM calls.',why:'Specialized agents can work with relevant dependencies, reusable tools, validators, and model strategies rather than an undifferentiated context window.'});
Object.assign(content.validate,{body:'Evaluation, consistency checks, validation, and automated repair are part of generation. Unit and E2E tests support application checking; observability makes individual calls, failures, and agent trajectories inspectable.',why:'Enterprise integration and business-logic failures need traceable feedback that can drive targeted repairs.'});
Object.assign(repair.spec,{title:'An enterprise API contract changes.',body:'Imagine an internal ERP API contract changes after connected application modules have been generated. This illustrative scenario explores the dependencies, context, and checks involved in repairing the affected work.',trace:'01 · Example: an ERP API contract used by an application module changes.'});
const four=document.createElement('section');four.className='lensing-sections';four.setAttribute('aria-labelledby','lensing-architecture-title');four.innerHTML=`<div class="eyebrow">Architecture in detail / Four areas</div><h3 id="lensing-architecture-title">From business requirements to a validated build.</h3><div class="system-copy">
<article><div class="eyebrow">01 / Specification & compiler</div><h4>Turn enterprise requirements into coordinated work.</h4><p>Architected and implemented the <strong>AI compiler and code-generation pipeline</strong>, connecting specification generation, specialized building agents, tools, models, validators, and repair stages. I work on these systems within the larger AISpecify team.</p></article>
<article><div class="eyebrow">02 / Graph orchestration & context</div><h4>Represent what depends on what.</h4><p><strong>Designed and built the graph-based orchestration architecture</strong> across agents, tools, generation stages, and application artifacts. Built graph-driven context selection, targeted artifact and business-context injection, and conversation-state management to narrow the information supplied to each LLM call.</p></article>
<article><div class="eyebrow">03 / Agent harness & execution</div><h4>Make agent workflows extensible.</h4><p>Built a <strong>plugin-based agent harness and agent-loop generation foundation</strong> so teams can compose tools, validators, context providers, and model strategies. Model routing, MCP-based enterprise integrations, and parallel execution support complex application-building workflows.</p></article>
<article><div class="eyebrow">04 / Observability, evaluation & repair</div><h4>Understand behavior and close the feedback loop.</h4><p><strong>Designed and built the observability and evaluation layer</strong> capturing every LLM call, agent execution and trajectory, tool invocation, model decision, latency, failure, and orchestration step. This supports architecture comparisons, production debugging, consistency checking, validation, and automated self-repair.</p></article></div></section>`;
lensing.querySelector('.ownership').replaceWith(four);
const cost=document.createElement('p');cost.className='system-footnote';cost.textContent='Routing, parallelization, and context/prompt caching reduced processing costs by up to 60%—a separate measure from the overall ~9× generation-cost improvement.';four.append(cost);
select(active);
const hich=document.querySelector('#hich .company-content');
hich.innerHTML=`<div class="architecture-intro"><div class="eyebrow">Hich / Profiling, trust & personalized content</div><h3>Three systems. Connected where it matters.</h3><p>Hich’s social polling platform brings together user responses, generated questions, and personalized recommendations. My work covered <strong>User Profiling, User Legitimacy, Content & Recommendations, and a separate Gamification layer</strong>. Trust and content quality inform recommendations through distinct signals.</p></div>
<div class="subsystem-map" role="group" aria-label="Hich architecture: three separate subsystems with a legitimacy-score input to recommendations">
<section class="subsystem legitimacy-system" aria-labelledby="legitimacy-title"><div class="eyebrow">Subsystem 01 / Trust</div><h4 id="legitimacy-title">User Legitimacy System</h4><p class="system-description">An independent ML pipeline estimating the reliability of a user’s responses and activities.</p><div class="architecture-node">User data & behavioral signals</div><div class="flow-down" aria-hidden="true">↓</div><div class="architecture-node">User Profiling & feature engineering<small>Statistical features + extensive profiling-derived features</small></div><div class="flow-down" aria-hidden="true">↓</div><div class="architecture-node">ML model<small>Model training → scoring pipeline</small></div><div class="flow-down" aria-hidden="true">↓</div><div class="architecture-node output">Legitimacy Score<small>Reliability of responses and platform activity</small></div><div class="system-port">OUTPUT → Recommendation system<br>A trust signal—not a content-generation step.</div></section>
<section class="subsystem content-system" aria-labelledby="content-system-title"><div class="eyebrow">Subsystem 02 / Content & discovery</div><h4 id="content-system-title">Content & Recommendation System</h4><p class="system-description">Content generation and quality scoring connect to a multi-algorithm recommendation pipeline.</p><div class="architecture-node">LLM content-generation orchestration<small>Region · Question type · Personality type · Other categories</small></div><div class="flow-down" aria-hidden="true">↓</div><div class="architecture-node">Content quality scoring<small>LLaVA-1.6 Vicuna-7B + LoRA<br>Fine-tuned on 1.7M moderator-labeled samples</small></div><div class="flow-down" aria-hidden="true">↓ quality-scored content</div><div class="system-port input">INPUT ← Legitimacy Score from Subsystem 01<br>Trust signal used by recommendations.</div><div class="algorithm-family"><div class="eyebrow">Recommendation algorithms / Parallel candidates</div><div class="algorithm-options"><span>Clustering</span><span>Collaborative filtering</span><span>Content-based ranking</span><span>Other recommendation algorithms</span></div></div><div class="flow-down" aria-hidden="true">↓ combine candidates</div><div class="architecture-node output">Shared Recommendation Pool<small>Higher-quality content is recommended more frequently.</small></div><div class="flow-down" aria-hidden="true">↓</div><div class="architecture-node">Periodic reprocessing & distribution<small>Recommendations redistributed to users approximately every 30 minutes.</small></div></section>
<section class="subsystem gamification-system" aria-labelledby="gamification-title"><div class="eyebrow">Subsystem 03 / Engagement</div><h4 id="gamification-title">Gamification System</h4><div class="architecture-node">Gamification & user engagement<small>A separate platform layer supporting participation.</small></div><p class="system-description">Designed around the platform, not inserted into the content-generation or recommendation pipeline. No unconfirmed service dependencies are shown.</p></section>
</div><p class="map-caption">Conceptual architecture based on my work. Arrows inside each subsystem show its flow; labeled ports show the Legitimacy Score passed to recommendations. Gamification remains separate. No customer data or internal service endpoints are exposed.</p>
<div class="ownership-callout"><strong>End-to-end ownership:</strong> I designed and implemented the complete User Legitimacy pipeline—from feature engineering and user profiling to model training and production scoring. Its output became a reusable signal for other parts of the platform, particularly recommendations.</div>
<div class="system-copy">
<article><div class="eyebrow">01 / Profiling & legitimacy</div><h4>Model the reliability of user activity.</h4><p>Combined user information, behavioral signals, statistical features, and extensive <strong>User Profiling-derived features</strong> to train an ML model producing a <strong>Legitimacy Score</strong>. The scoring pipeline estimates how reliable a user’s responses and activities are; it operates independently of content generation.</p></article>
<article><div class="eyebrow">02 / Content orchestration</div><h4>Generate questions for different audiences.</h4><p>Built <strong>LLM-powered content and question generation</strong> orchestrated around region, question type, personality type, and other categories. Integrated external news sources and semantic retrieval to support relevant content workflows. These pipelines increased interactions by <strong>14%</strong> and average session time by <strong>8%</strong>.</p></article>
<article><div class="eyebrow">03 / Multimodal quality scoring</div><h4>Score generated content before recommendation.</h4><p>Fine-tuned <strong>LLaVA-1.6 Vicuna-7B with LoRA</strong> on <strong>1.7M moderator-labeled samples</strong>, achieving <strong>98.1% content-quality scoring accuracy</strong>. Generated items pass through this model, and their quality scores inform recommendation value and frequency.</p></article>
<article><div class="eyebrow">04 / Recommendation pool</div><h4>Combine multiple approaches to discovery.</h4><p>Designed an event-driven recommendation platform with <strong>Kafka and ClickHouse</strong>, combining clustering, collaborative filtering, content-based ranking, and other algorithms. Candidates enter a <strong>shared Recommendation Pool</strong> for reprocessing and redistribution approximately <strong>every 30 minutes</strong>. Legitimacy and content-quality scores inform recommendations as distinct signals.</p></article>
<article><div class="eyebrow">05 / Gamification</div><h4>Design a separate engagement layer.</h4><p>Designed a substantial <strong>gamification and user-engagement layer</strong> around the platform. This is a separate subsystem, not a stage between content generation, scoring, and recommendation. Specific mechanics can be detailed separately.</p></article>
<article><div class="eyebrow">06 / Production monitoring</div><h4>Observe quality, behavior, and business outcomes.</h4><p>Implemented <strong>Grafana monitoring</strong> for model quality, user engagement, system behavior, and business KPIs. Fraud detection and user-legitimacy scoring improved content-quality accuracy by <strong>43%</strong> and monthly revenue by over <strong>60%</strong>, as reported for that work.</p></article>
</div><div class="outcomes"><div class="metric"><div class="metric-value blue">+18%</div><p>User activity from recommendation improvements</p></div><div class="metric"><div class="metric-value blue">−33%</div><p>Post skipping</p></div><div class="metric"><div class="metric-value blue">+13%</div><p>Average usage</p></div></div><div class="company-source"><span>Hich · AI Software Engineer · Birmingham, UK (Remote)</span><a href="https://www.linkedin.com/company/hichapp/" target="_blank" rel="noopener noreferrer">About Hich ↗</a></div>`;
})();
