(() => {
const hero=document.querySelector('.hero');
hero.outerHTML="<section class=\"personal-screen personal-hero\" id=\"home\" aria-labelledby=\"greeting\"><header class=\"topbar\"><span class=\"personal-mono\">Mohsen Shahverdi</span><a href=\"mailto:mohsen.shahverdi97@gmail.com\">Say hello ↗</a></header><div class=\"hero-content\"><img class=\"portrait\" src=\"assets/mohsen-shahverdi.jpg\" alt=\"Mohsen smiling\"><div class=\"personal-mono\">AI engineer · Curious by nature</div><h1 id=\"greeting\">Hi, I’m Mohsen. <span class=\"wave\">👋</span></h1><p class=\"personal-intro\">I like building things.<br>And figuring out how they work.</p><p class=\"coffee\">A good problem, a little curiosity, and a coffee. ☕</p><nav aria-label=\"Portfolio\"><a href=\"#about\">ABOUT</a><a href=\"#experience\">EXPERIENCE</a><a href=\"#skills\">SKILLS</a><a href=\"#research\">RESEARCH</a><a href=\"#education\">EDUCATION</a></nav><div class=\"socials\"><a href=\"https://github.com/mohsenshahverdy\">GitHub ↗</a><a href=\"https://www.linkedin.com/in/mohsen-shahverdi/\">LinkedIn ↗</a><a href=\"assets/Mohsen-Shahverdi-Senior-AI-Engineer-CV.pdf\">CV ↓</a></div></div><div class=\"bottom-note\"><a href=\"#about\">A LITTLE MORE ABOUT ME ↓</a><span>Lensing AI · Heidelberg, Germany</span></div></section><section class=\"personal-screen personal-about\" id=\"about\" aria-labelledby=\"about-title\"><div class=\"about-label\"><span class=\"personal-mono\">01 / The person behind the code</span></div><div class=\"about-grid\"><figure class=\"photo-wrap\" style=\"margin:0\"><img class=\"about-photo\" src=\"assets/mohsen-shahverdi.jpg\" alt=\"Mohsen outdoors\"><figcaption class=\"photo-caption\">AI, mathematics, and plenty of questions. ☕</figcaption></figure><div><h2 id=\"about-title\">The code is interesting.<br><span>The “why” keeps me curious.</span></h2><p>I’m an AI engineer at <strong>Lensing AI</strong>, working on agents and the systems around them. I like moving between an idea, an experiment, and something that actually works.</p><p>But I’m especially drawn to <strong>mathematical problems, statistics, and the theory behind machine learning</strong>. Using a model is one thing; understanding its assumptions, uncertainty, and why it learns is the part I want to keep exploring.</p><aside class=\"math-note\"><div class=\"personal-mono\">∑ &nbsp; The questions I come back to</div><p>Why does it generalize?<br>What are we assuming? How sure are we?</p></aside><p>That curiosity also takes me into <strong>evolutionary biology and philosophy</strong>. And away from the screen, I’m happy with good food, a coffee, or a game of chess.</p><div class=\"interests\" aria-label=\"Other interests\"><span>☕ Coffee</span><span>🍜 Food</span><span>♟️ Chess</span><span>🧬 Evolution</span><span>💭 Philosophy</span></div></div></div><footer class=\"about-footer\"><a href=\"#home\">↑ Back to hello</a><a href=\"#experience\">Next chapter: things I’ve worked on →</a></footer></section>";
const exp=document.getElementById('work');exp.id='experience';exp.querySelector('.section-bar .eyebrow').textContent='02 / Experience';
document.querySelectorAll('a[href="#work"]').forEach(a=>a.href='#experience');
const skills=document.createElement('section');skills.id='skills';skills.className='skills-section';skills.setAttribute('aria-labelledby','skills-heading');
const groups=[['01','Agent systems','Multi-agent orchestration · AI compiler workflows · Agent runtimes · Dependency graphs · Context engineering · MCP & tool calling · Model routing · Plugin architectures · Observability & evaluation'],['02','Machine learning & research','LoRA / PEFT · Fine-tuning · PyTorch · Hugging Face · TensorFlow · scikit-learn · XGBoost · NLP · Computer vision · Cooperative 3D perception · Recommendation systems'],['03','Software engineering','Python · TypeScript · Node.js · FastAPI · Flask · REST APIs · Distributed systems · System design · Unit & E2E testing · CI/CD · Git'],['04','Data & infrastructure','PostgreSQL · SQL · ClickHouse · Redis · Kafka · MongoDB · PySpark · Docker · AWS · Grafana · Metabase']];
skills.innerHTML='<div class="section-bar"><span class="eyebrow" id="skills-heading">03 / Skills</span><span class="right">The tools behind the work</span></div><div class="skills-grid-web">'+groups.map(([n,title,text])=>`<article class="skill-group"><div class="eyebrow">${n} / Engineering toolkit</div><h3>${title}</h3><p>${text}</p></article>`).join('')+'</div>';exp.after(skills);
document.getElementById('research-heading').textContent='04 / Research projects';document.getElementById('education-heading').textContent='05 / Education';
const headerNav=document.querySelector('header nav');headerNav.querySelectorAll('a').forEach(a=>a.remove());
const socials=document.createElement('a');socials.className='social-link';socials.href='mailto:mohsen.shahverdi97@gmail.com';socials.textContent='Get in touch ↗';headerNav.prepend(socials);

const siteHeader=document.querySelector('.wrap > header');
document.querySelector('.topbar').append(document.querySelector('.theme-control'));
siteHeader.hidden=true;
const animatedHero=document.querySelector('.personal-hero');
animatedHero.insertAdjacentHTML('afterbegin','<canvas class="hero-canvas" aria-hidden="true"></canvas>');
animatedHero.insertAdjacentHTML('beforeend','<button class="motion-toggle" type="button" aria-pressed="false">Pause animation</button>');
const canvas=animatedHero.querySelector('canvas'),ctx=canvas.getContext('2d'),control=animatedHero.querySelector('.motion-toggle');
const reduced=matchMedia('(prefers-reduced-motion: reduce)');let paused=reduced.matches,visible=true,raf=0,w=0,h=0,points=[],last=0;
function resize(){const rect=animatedHero.getBoundingClientRect();w=rect.width;h=rect.height;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);points=Array.from({length:w<600?32:64},(_,i)=>({x:((i*137.51)%997)/997*w,y:((i*241.73)%991)/991*h,vx:Math.sin(i*2.4)*.11,vy:Math.cos(i*1.7)*.11}));draw(0)}
function draw(dt){const light=document.documentElement.dataset.theme==='light';const rgb=light?'56,100,129':'148,190,222';ctx.clearRect(0,0,w,h);points.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.x<0||p.x>w)p.vx*=-1;if(p.y<0||p.y>h)p.vy*=-1});
for(let i=0;i<points.length;i++){const a=points[i];for(let j=i+1;j<points.length;j++){const b=points[j],dist=Math.hypot(a.x-b.x,a.y-b.y);if(dist<155){ctx.strokeStyle=`rgba(${rgb},${(1-dist/155)*.29})`;ctx.lineWidth=.7;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}ctx.fillStyle=`rgba(${rgb},.55)`;ctx.beginPath();ctx.arc(a.x,a.y,i%7===0?2:1.2,0,Math.PI*2);ctx.fill()}
}
function frame(now){raf=0;const dt=last?Math.min((now-last)/16.67,2):1;last=now;draw(dt);if(!paused&&visible&&!document.hidden)raf=requestAnimationFrame(frame)}
function schedule(){cancelAnimationFrame(raf);raf=0;last=0;control.textContent=paused?'Play animation':'Pause animation';control.setAttribute('aria-pressed',String(paused));animatedHero.classList.toggle('motion-off',paused);if(!paused&&visible&&!document.hidden)raf=requestAnimationFrame(frame);else draw(0)}
control.addEventListener('click',()=>{paused=!paused;schedule()});reduced.addEventListener('change',()=>{paused=reduced.matches;schedule()});document.addEventListener('visibilitychange',schedule);
new ResizeObserver(resize).observe(animatedHero);new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;schedule()}).observe(animatedHero);new MutationObserver(()=>draw(0)).observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});resize();schedule();
})();
