(() => {
const hero = document.querySelector('.hero');
const oldAside = hero.querySelector('.about-aside');
const about = document.createElement('section');
about.id='about';about.className='about-section';about.setAttribute('aria-labelledby','about-heading');
about.innerHTML='<div class="section-bar"><span class="eyebrow" id="about-heading">01 / About</span><span class="right">A little about me</span></div><div class="about-copy"><div><h2>Curiosity, experiments,<br>and production systems.</h2><p>I’m an AI engineer working across agent architectures, machine learning, and the infrastructure that brings them into production. I enjoy understanding how a system behaves—and building the tools to make it better.</p></div></div>';
about.querySelector('.about-copy').append(oldAside);hero.after(about);
const photo=document.querySelector('.identity img').getAttribute('src');
hero.innerHTML=`<canvas class="hero-canvas" aria-hidden="true"></canvas><div class="hero-content"><img class="hero-portrait" src="${photo}" alt="Mohsen Shahverdi"><div class="eyebrow">Senior AI Engineer · Applied research</div><h1 id="hero-title">Hi, I’m Mohsen.</h1><p class="hero-tagline">Building intelligent systems.<br>Understanding what makes them work.</p><p class="hero-location">Lensing AI · Heidelberg, Germany</p><nav class="chapter-nav" aria-label="Explore portfolio sections"><a href="#about">About</a><a href="#experience">Experience</a><a href="#skills">Skills</a><a href="#research">Research</a><a href="#education">Education</a></nav><div class="hero-links"><a href="https://github.com/mohsenshahverdy" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a href="https://www.linkedin.com/in/mohsen-shahverdi/" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="assets/Mohsen-Shahverdi-Senior-AI-Engineer-CV.pdf" download>Download CV ↓</a></div></div><a class="scroll-cue" href="#about"><span aria-hidden="true"></span>SCROLL TO EXPLORE</a><button class="motion-toggle" type="button" aria-pressed="false">Pause animation</button>`;
const exp=document.getElementById('work');exp.id='experience';exp.querySelector('.section-bar .eyebrow').textContent='02 / Experience';
document.querySelectorAll('a[href="#work"]').forEach(a=>a.href='#experience');
const skills=document.createElement('section');skills.id='skills';skills.className='skills-section';skills.setAttribute('aria-labelledby','skills-heading');
const groups=[['01','Agent systems','Multi-agent orchestration · AI compiler workflows · Agent runtimes · Dependency graphs · Context engineering · MCP & tool calling · Model routing · Plugin architectures · Observability & evaluation'],['02','Machine learning & research','LoRA / PEFT · Fine-tuning · PyTorch · Hugging Face · TensorFlow · scikit-learn · XGBoost · NLP · Computer vision · Cooperative 3D perception · Recommendation systems'],['03','Software engineering','Python · TypeScript · Node.js · FastAPI · Flask · REST APIs · Distributed systems · System design · Unit & E2E testing · CI/CD · Git'],['04','Data & infrastructure','PostgreSQL · SQL · ClickHouse · Redis · Kafka · MongoDB · PySpark · Docker · AWS · Grafana · Metabase']];
skills.innerHTML='<div class="section-bar"><span class="eyebrow" id="skills-heading">03 / Skills</span><span class="right">The tools behind the work</span></div><div class="skills-grid-web">'+groups.map(([n,title,text])=>`<article class="skill-group"><div class="eyebrow">${n} / Engineering toolkit</div><h3>${title}</h3><p>${text}</p></article>`).join('')+'</div>';exp.after(skills);
document.getElementById('research-heading').textContent='04 / Research projects';document.getElementById('education-heading').textContent='05 / Education';
const headerNav=document.querySelector('header nav');headerNav.querySelectorAll('a').forEach(a=>a.remove());
const socials=document.createElement('a');socials.className='social-link';socials.href='mailto:mohsen.shahverdi97@gmail.com';socials.textContent='Get in touch ↗';headerNav.prepend(socials);
const canvas=hero.querySelector('canvas'),ctx=canvas.getContext('2d'),control=hero.querySelector('.motion-toggle');
const reduced=matchMedia('(prefers-reduced-motion: reduce)');let paused=reduced.matches,visible=true,raf=0,w=0,h=0,points=[],last=0;
function resize(){const rect=hero.getBoundingClientRect();w=rect.width;h=rect.height;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);points=Array.from({length:w<600?32:64},(_,i)=>({x:((i*137.51)%997)/997*w,y:((i*241.73)%991)/991*h,vx:Math.sin(i*2.4)*.11,vy:Math.cos(i*1.7)*.11}));draw(0)}
function draw(dt){const light=document.documentElement.dataset.theme==='light';const rgb=light?'56,100,129':'148,190,222';ctx.clearRect(0,0,w,h);points.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.x<0||p.x>w)p.vx*=-1;if(p.y<0||p.y>h)p.vy*=-1});
for(let i=0;i<points.length;i++){const a=points[i];for(let j=i+1;j<points.length;j++){const b=points[j],dist=Math.hypot(a.x-b.x,a.y-b.y);if(dist<155){ctx.strokeStyle=`rgba(${rgb},${(1-dist/155)*.29})`;ctx.lineWidth=.7;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}ctx.fillStyle=`rgba(${rgb},.55)`;ctx.beginPath();ctx.arc(a.x,a.y,i%7===0?2:1.2,0,Math.PI*2);ctx.fill()}
ctx.strokeStyle=`rgba(${rgb},.1)`;ctx.lineWidth=.8;[.35,.47].forEach(r=>{ctx.beginPath();ctx.arc(w/2,h/2,Math.min(w,h)*r,0,Math.PI*2);ctx.stroke()})}
function frame(now){raf=0;const dt=last?Math.min((now-last)/16.67,2):1;last=now;draw(dt);if(!paused&&visible&&!document.hidden)raf=requestAnimationFrame(frame)}
function schedule(){cancelAnimationFrame(raf);raf=0;last=0;control.textContent=paused?'Play animation':'Pause animation';control.setAttribute('aria-pressed',String(paused));hero.classList.toggle('motion-off',paused);if(!paused&&visible&&!document.hidden)raf=requestAnimationFrame(frame);else draw(0)}
control.addEventListener('click',()=>{paused=!paused;schedule()});reduced.addEventListener('change',()=>{paused=reduced.matches;schedule()});document.addEventListener('visibilitychange',schedule);
new ResizeObserver(resize).observe(hero);new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;schedule()}).observe(hero);new MutationObserver(()=>draw(0)).observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});resize();schedule();
})();
