(() => {
  const list = document.querySelector('#research .academic-list');
  if (!list) return;
  const repo = 'https://github.com/mohsenshahverdy/PostTrain-Forge';
  const source = `${repo}/blob/9c9465029827905830724ef97b2320a3e4603ef7`;
  const methods = [
    ['Supervised & preferences', 'Different objectives. Explicit training targets.', 'Response/action-masked SFT excludes prompts, padding, and environment observations from supervision. Sigmoid and hinge DPO, IPO, SimPO, ORPO, and unary KTO retain their own scoring and reference-policy conventions.', 'Inspect the target mask, chosen/rejected scores, reference roles, and loss diagnostics.'],
    ['Rewards & online RL', 'Keep the learning signal inspectable.', 'Bradley–Terry reward modeling, REINFORCE, actor-critic with GAE, PPO, and critic-free GRPO share model and runtime infrastructure. Online updates retain exact sampled action tokens and fixed behavior-policy scores.', 'Inspect reward components, policy ratios, advantages, and zero-variance groups. Valid syntax and task success remain separate measurements.'],
    ['Tool-using agents', 'Train against an environment you can replay.', 'Typed reset/step environments separate tools, JSON schemas, parsers, observations, and task sources. A local synthetic issue tracker supports replay-verified demonstrations, reward-ranked preference trajectories, and synchronous closed-loop rollouts.', 'Re-execute recorded actions from the same seed and verify transitions and final state. Tiny examples establish mechanics, not useful pretrained-agent quality.']
  ];
  const views = [
    ['Model explorer', 'model-3d.png', 'A metadata-driven view of model stacks, blocks, and submodules.', 'The isolated 3D preview explains architecture and tensor dimensions. It does not display measured activations or inspect trained weights.'],
    ['Pipeline builder', 'pipeline-editor.png', 'Compose typed components, validate a graph, and inspect its execution plan.', 'Actual repository screenshot of a two-node runtime smoke pipeline. It illustrates composition, not a model-training result.'],
    ['Run inspector', 'run-metrics.png', 'Inspect metrics alongside configuration, events, artifacts, and lineage.', 'Actual repository screenshot of smoke-test runtime telemetry. These values are not learning curves or model-quality benchmarks.']
  ];
  const card = document.createElement('details');
  card.className = 'company-card research-card'; card.id = 'research-posttrain';
  card.innerHTML = `<summary><span class="company-logo initials">PF</span><span><span class="company-title">PostTrain Forge</span><span class="company-role">Independent research engineering</span><span class="company-domain">Language models · Agent training · Reproducible experiments</span></span><span class="company-date">Research toolkit<small>Python · PyTorch · Local dashboard</small></span><span class="company-toggle" aria-hidden="true"></span></summary>
  <div class="company-content forge-content">
    <div class="thesis-intro"><div><div class="eyebrow">Post-training / Models & tool-using agents</div><h3>Study the learning.<br>Inspect the system.</h3></div><div><p>I’m building <strong>PostTrain Forge</strong> to train, evaluate, and inspect language models and agents through reusable components. It brings algorithm implementations, shared model infrastructure, reproducible execution, and a local dashboard into one research toolkit.</p><p>The question behind it: how can I change a learning objective without rebuilding the infrastructure—and still understand exactly what happened?</p></div></div>
    <div class="research-links"><a href="${repo}" target="_blank" rel="noopener noreferrer">Explore repository ↗</a><a href="${source}/docs/architecture/overview.md" target="_blank" rel="noopener noreferrer">Architecture ↗</a><a href="${source}/docs/release/support.md" target="_blank" rel="noopener noreferrer">Support & evidence ↗</a></div>
    <section class="thesis-panel forge-gallery" aria-labelledby="forge-visual-title"><div class="eyebrow">01 / Inside the toolkit</div><h4 id="forge-visual-title">From a component to an inspectable experiment.</h4><div class="thesis-controls" aria-label="Project screenshots">${views.map((v,i)=>`<button type="button" data-forge-view="${i}" aria-pressed="${i===0}">${v[0]}</button>`).join('')}</div><figure><a id="forge-image-link" target="_blank" rel="noopener noreferrer"><img id="forge-image" loading="lazy" width="1920" height="1080" alt=""></a><figcaption id="forge-caption" aria-live="polite"></figcaption></figure></section>
    <section class="thesis-panel" aria-labelledby="forge-method-title"><div class="eyebrow">02 / Learning objectives</div><h4 id="forge-method-title">The algorithm changes. The infrastructure stays shared.</h4><div class="thesis-controls" aria-label="Training method families">${methods.map((m,i)=>`<button type="button" data-forge-method="${i}" aria-pressed="${i===0}">${m[0]}</button>`).join('')}</div><div id="forge-method" aria-live="polite"></div></section>
    <section class="thesis-panel" aria-labelledby="forge-runtime-title"><div class="eyebrow">03 / Configuration to evidence</div><h4 id="forge-runtime-title">Validate before loading. Record what actually ran.</h4><ol class="forge-pipeline"><li><span>01 / DEFINE</span><strong>Typed experiment</strong><p>Hydra configuration or portable YAML/JSON pipeline graphs.</p></li><li><span>02 / COMPILE</span><strong>Execution plan</strong><p>Check schemas, ports, versions, capabilities, and cycles.</p></li><li><span>03 / EXECUTE</span><strong>Shared capabilities</strong><p>Local workers, model loading, adapters, rewards, and checkpoints.</p></li><li><span>04 / INSPECT</span><strong>Reproducible evidence</strong><p>Separate metrics, events, artifacts, and identity manifests.</p></li></ol><p>Immutable pipeline revisions bind a run to its definition. CLI, HTTP API, and dashboard share services. Worker heartbeats and restart reconciliation expose lost execution without silently retrying training.</p></section>
    <div class="thesis-bottom"><section class="thesis-panel"><div class="eyebrow">04 / Model preparation</div><h4>Selection is not certification.</h4><p>A catalog of <strong>108 model descriptors across 26 families</strong> separates discovery from revision resolution, caching, loading, and exact-configuration checks. Browsing does not download weights.</p><p>LoRA, rsLoRA, DoRA, AdaLoRA, PiSSA, and LoftQ are configurable strategies. Low-bit preparation includes NF4/FP4 and 8-bit paths; lineage records the base model and ordered adaptation, quantization, and merge stages.</p><p class="thesis-note">Catalog snapshot: 9c94650. A listed model or adapter does not imply every device/configuration combination is validated.</p></section><section class="thesis-panel"><div class="eyebrow">05 / Experimental workflow</div><h4>Compare runs without losing their identity.</h4><p>The dashboard connects live SSE updates, logs, selectable metrics, and safe artifact inspection. Compare configurations, pipeline structure, lineage, and results; expand model × seed × repetition matrices into traceable runs.</p><p>Checkpoints preserve optimizer, scheduler, progress, and RNG state. Portable model/adapter exports remain separate and undergo fresh-process reload checks.</p><p class="thesis-note">3D pipeline and model explorers are isolated, metadata-driven previews. Local benchmark model cells execute sequentially.</p></section></div>
    <details class="forge-boundaries"><summary>Tested scope, limitations & release status</summary><div><p>Recorded release evidence includes six bounded installed-wheel CPU/A40 profiles covering SFT, DPO, and single-GPU NF4 QLoRA. Single-node replicated DDP evidence covers SFT/DPO; it does not certify every training method. Continuation requires compatible identities and the same world size.</p><p>This is a <strong>trusted single-user research tool</strong>, not an authenticated hosted service. Remote transport, multi-node/elastic training, FSDP/ZeRO, and distributed online-agent collection are not implemented. Gemma 4 is catalog-only.</p><p>The release audit records remaining publication blockers: a repository license decision and an upstream dependency advisory. Public source availability does not imply an open-source license grant.</p><a href="${source}/reports/release/release_readiness.md" target="_blank" rel="noopener noreferrer">Read the release evidence and blockers ↗</a></div></details>
    <p class="forge-source">Based on repository revision <a href="${repo}/tree/9c9465029827905830724ef97b2320a3e4603ef7" target="_blank" rel="noopener noreferrer">9c94650 ↗</a>. Screenshots are from the repository; no benchmark was rerun for this portfolio.</p>
  </div>`;
  list.prepend(card);
  function view(i) {
    const v=views[i], path=`assets/posttrain/${v[1]}`;
    card.querySelectorAll('[data-forge-view]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.forgeView)===i)));
    const img=card.querySelector('#forge-image'); img.src=path; img.alt=v[2];
    const link=card.querySelector('#forge-image-link'); link.href=path; link.setAttribute('aria-label',`Open ${v[0]} screenshot at full resolution`);
    card.querySelector('#forge-caption').textContent=`${v[2]} ${v[3]} Open image at full resolution ↗`;
  }
  function method(i) {
    const m=methods[i];
    card.querySelectorAll('[data-forge-method]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.forgeMethod)===i)));
    const panel=card.querySelector('#forge-method'); panel.replaceChildren();
    for(const [tag,txt] of [['h4',m[1]],['p',m[2]],['p',m[3]]]){const el=document.createElement(tag);el.textContent=txt;panel.append(el)}
  }
  card.querySelectorAll('[data-forge-view]').forEach(b=>b.addEventListener('click',()=>view(Number(b.dataset.forgeView))));
  card.querySelectorAll('[data-forge-method]').forEach(b=>b.addEventListener('click',()=>method(Number(b.dataset.forgeMethod))));
  view(0);method(0);
})();
