(() => {
  const card = document.querySelector('#research-v2v .company-content');
  if (!card) return;
  const repo = 'https://github.com/mohsenshahverdy/receiver-driven-sparse-v2v-3d-presentation';
  const methods = [
    ['Dense & sender Top-K', 'Establish the communication–accuracy baseline.', 'PointPillars encodes LiDAR into bird’s-eye-view (BEV) features, followed by V2VAM intermediate fusion. Dense sharing provides the reference; sender-side Top-K selects high-energy feature cells under a sparse budget.', ['LiDAR → BEV features', 'Dense / energy-ranked cells', 'Intermediate fusion → 3D detection']],
    ['Receiver requests', 'Ask for the evidence the receiver needs.', 'The receiver combines ego need with compact collaborator context. A normalized need × context score ranks cells for a Top-K request, moving the selection decision from the sender to the receiving vehicle.', ['Ego need + compact context', 'Need × context → Top-K request', 'Requested BEV cells → fusion']],
    ['Temporal cache', 'Use history to refine the next request.', 'Receiver-owned cached context adds novelty, age, and confidence to request selection. The cache is compact request state—not a hidden dense feature transmission before the request.', ['Cached context + new context', 'Novelty · age · confidence', 'Updated request → sparse sharing']],
    ['Learned policy', 'Learn which cells deserve the budget.', 'A lightweight CNN with 3,217 trainable parameters combines ego need, collaborator context, cache, novelty, age, and confidence. A hard Top-K selection turns its scores into sparse requests at inference.', ['Need · context · temporal state', 'Trained request head → cell scores', 'Hard Top-K → requested features']]
  ];
  const splits = {
    carla: {name:'CARLA',frames:'2,170 CARLA 2021-only frames',image:'carla_frame_000011_receiver_progression.png',scene:'Frame 000011: the learned policy recovers two objects missed by the temporal policy in this selected example.',rows:[['Dense', '1.0000', '0.8134', '0.9824'],['Sender Top-K', '0.0953', '0.8172', '0.9517'],['Learned temporal', '0.0983', '0.7945', '0.9765']],note:'Sender Top-K has the strongest global AP here. The learned policy trades some AP for higher trajectory-time risk recall, while using about 9.8% of dense communication.'},
    culver: {name:'Culver City',frames:'550 Culver City frames',image:'culver_frame_000313_receiver_progression.png',scene:'Frame 000313: a second qualitative comparison of receiver, temporal, and learned request policies.',rows:[['Dense', '1.0000', '0.7291', '0.9765'],['Sender Top-K', '0.0873', '0.7083', '0.8811'],['Learned temporal', '0.0904', '0.7277', '0.9703']],note:'On this split, the learned policy approaches dense AP and trajectory-time risk recall at about 9.0% of dense communication. This is a split-specific result, not a claim of universal superiority.'}
  };
  card.innerHTML = `<div class="thesis-intro"><div><div class="eyebrow">Master’s thesis / Cooperative 3D perception</div><h3>What should a vehicle ask its neighbors to see?</h3></div><p>I investigate <strong>receiver-driven sparse V2V communication</strong>: selecting intermediate features that help a vehicle detect objects, without exchanging the full feature map. The central question is whether receiver need and temporal context can preserve useful perception under a limited communication budget.</p></div>
  <div class="thesis-panel"><div class="thesis-panel-heading"><div><div class="eyebrow">01 / Method & experimental progression</div><h4>From sender selection to learned requests.</h4></div></div><div class="thesis-controls" aria-label="Explore communication policies">${methods.map((m,i)=>`<button type="button" data-method="${i}" aria-pressed="${i===0}">${m[0]}</button>`).join('')}</div><div id="thesis-method" aria-live="polite"></div><p class="thesis-note">Controlled comparison: vary communication policy at the BEV fusion boundary while retaining the detector architecture. Learned-policy results require trained request-head weights; untrained debug runs are not reportable.</p></div>
  <div class="thesis-panel"><div class="thesis-panel-heading"><div><div class="eyebrow">02 / Scene evidence & reported evaluation</div><h4>Inspect detections. Then compare the trade-off.</h4></div><div class="thesis-controls" aria-label="Evaluation split"><button type="button" data-split="carla" aria-pressed="true">CARLA</button><button type="button" data-split="culver" aria-pressed="false">Culver City</button></div></div><div id="thesis-evidence" aria-live="polite"></div></div>
  <div class="thesis-bottom"><div class="thesis-panel"><div class="eyebrow">03 / Evaluation design</div><h4>Detection accuracy is only one lens.</h4><p><strong>AP at 3D IoU 0.5 and 0.7</strong> measures detection quality. Danger-zone and risk-weighted recall focus on ego-relevant objects; trajectory-aware metrics account for future proximity and urgency.</p><p>Communication accounting includes feature, context, and metadata bytes. Qualitative plots inspect true positives, false positives, and missed ground-truth objects—not inferred sparse masks.</p></div><div class="thesis-panel"><div class="eyebrow">04 / Reproducible research</div><h4>From policy hypothesis to inspectable evidence.</h4><p>Policy implementations, configuration-driven experiments, checkpoint guards, tests, and scene-level inspection make the comparison auditable. The companion 3D presentation explains the occlusion problem and the progression of the methods.</p><p class="thesis-note">Trajectory metrics are safety-oriented perception proxies—not evidence of real-world driving safety. Tables below summarize reported presentation results, not new independent reproductions.</p></div></div>
  <div class="research-links"><a href="https://github.com/mohsenshahverdy/comm-aware-v2v-perception" target="_blank" rel="noopener noreferrer">Research code ↗</a><a href="${repo}" target="_blank" rel="noopener noreferrer">3D scenes & presentation ↗</a><a href="${repo}/blob/main/src/data/steps.js" target="_blank" rel="noopener noreferrer">Reported results & methodology ↗</a></div>`;
  function method(index) {
    const m=methods[index];
    card.querySelectorAll('[data-method]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.method)===index)));
    card.querySelector('#thesis-method').innerHTML=`<h4>${m[1]}</h4><p>${m[2]}</p><ol class="thesis-flow">${m[3].map((s,i)=>`<li><span>0${i+1}</span>${s}</li>`).join('')}</ol>`;
  }
  function split(key) {
    const s=splits[key];
    card.querySelectorAll('[data-split]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.split===key)));
    card.querySelector('#thesis-evidence').innerHTML=`<figure><a href="assets/research/${s.image}" target="_blank" rel="noopener noreferrer" aria-label="Open ${s.name} detection comparison at full resolution"><img src="assets/research/${s.image}" alt="${s.name} bird’s-eye-view detection comparison: receiver, temporal, and learned policies; full scene and region-of-interest views." loading="lazy" width="2669" height="1064"></a><figcaption>${s.scene} <span>Open image for full resolution ↗</span></figcaption></figure><div class="thesis-results"><div><div class="eyebrow">${s.frames}</div><div class="thesis-table-wrap"><table><caption>Selected reported policies · IoU 0.7</caption><thead><tr><th scope="col">Policy</th><th scope="col">Comm. ratio ↓</th><th scope="col">AP ↑</th><th scope="col">TTRR ↑</th></tr></thead><tbody>${s.rows.map(r=>`<tr>${r.map((v,i)=>i?`<td>${v}</td>`:`<th scope="row">${v}</th>`).join('')}</tr>`).join('')}</tbody></table></div></div><div><h4>What the comparison tells us</h4><p>${s.note}</p><p class="thesis-note">Communication ratio is relative to dense sharing. TTRR = trajectory-time risk recall. These are reported aggregate values; the scene above is illustrative, not the aggregate benchmark.</p></div></div>`;
  }
  card.querySelectorAll('[data-method]').forEach(b=>b.addEventListener('click',()=>method(Number(b.dataset.method))));
  card.querySelectorAll('[data-split]').forEach(b=>b.addEventListener('click',()=>split(b.dataset.split)));
  method(0);split('carla');
})();
